trigger:
  branches:
    include:
    - develop
    - refs/tags/*
  paths:
    exclude:
    - .azure-pipelines/release.yml
    - .azure-pipelines/pr.yml
    - README.md

pr: none

stages:
  - template: templates/codeQualityChecks.yml

  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'windows'
        timeoutInMinutes: 180
        displayName: 'Windows'
        condition: eq(1,1)
        pool:
          vmImage: 'windows-2019'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/windowsBuild.yml
          - template: templates/windowsPackage.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'
    
      - job: 'linux'
        timeoutInMinutes: 180
        displayName: 'Linux'
        condition: eq(1,0)
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/linuxBuild.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
    
      - job: 'osx'
        displayName: 'OSX'
        condition: eq(1,0)
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/osxBuild.yml
          - template: templates/osxPackage.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
